spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/bencol_system?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  file:
    name: logs/bencol-app.log

  level:
    root: INFO
    com.runicsoft.bencolapp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: INFO

security:
  jwt:
    secret: ${BENCOL_JWT_SECRET:12345678901234567890123456789012}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:120}

  admin:
    username: ${BENCOL_ADMIN_USERNAME:adminbencol}
    email: ${BENCOL_ADMIN_EMAIL:admin@bencol.com}
    password: ${BENCOL_ADMIN_PASSWORD:Admin123*}