spring:
  application:
    name: bencol-app

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jackson:
    serialization:
      indent_output: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

server:
  port: ${SERVER_PORT:8080}

bencol:
  storage:
    root: ${BENCOL_STORAGE_ROOT:uploads}