spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  file:
    name: ${LOG_FILE:logs/bencol-app.log}

  level:
    root: INFO
    com.runicsoft.bencolapp: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.springframework.web: WARN

security:
  jwt:
    secret: ${BENCOL_JWT_SECRET}
    expiration-minutes: ${JWT_EXPIRATION_MINUTES:480}

  admin:
    username: ${BENCOL_ADMIN_USERNAME}
    email: ${BENCOL_ADMIN_EMAIL}
    password: ${BENCOL_ADMIN_PASSWORD}

server:
  forward-headers-strategy: framework