ALTER TABLE empresas
    ADD COLUMN direccion VARCHAR(255) NULL,
ADD COLUMN telefono VARCHAR(20) NULL,
ADD COLUMN email VARCHAR(100) NULL,
ADD COLUMN logo_nombre VARCHAR(255) NULL,
ADD COLUMN logo_tipo VARCHAR(100) NULL,
ADD COLUMN logo_ruta VARCHAR(500) NULL;